# Global config.yml file to be used by all DTAG projects.
#
# This config uses a central ORT Artifactory Cache maintained by OpenSource@DTIT.
# The credentials are set globally in the entire github.com/telekom organization.
# If everyone contributes to the cache, scans will become much faster.
#
# If this config doesn't meet your needs, feel free to patch values in your
# workflows using yq or replacing the file entirely after cloning the repo.

ort:
  # Allows defining package configs/curations in the repository's .ort.yml file
  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # These could be used in the future to not treat warnings as severe issues
  #severeIssueThreshold: ERROR
  #severeRuleViolationThreshold: ERROR

  # Force overwriting of existing reports
  forceOverwrite: true

  analyzer:
    # Allow version ranges in dependency specifications
    allowDynamicVersions: true
    skipExcluded: true
  downloader:
    skipExcluded: true
    # Allow downloads using symbolic names that point to moving revisions, like Git branches
    allowMovingRevisions: true
  scanner:
    storages:
      # Read/write results to actions cache
      local:
        backend:
          localFileStorage:
            directory: /home/ort/.ort/scanner/results
            compression: false
      # Read/write results to OpenSource@DTIT ORT cache on artifactory
      artifactory:
        backend:
          httpFileStorage:
            url: "https://artifactory.devops.telekom.de/artifactory/open-source-dtit-ort-generic/ort/scan-results"
            headers:
              Authorization: "Bearer ${ORT_ARTIFACTORY_TOKEN}"
    storageReaders: ["local", "artifactory"]
    storageWriters: ["artifactory", "local"]
    skipExcluded: true
  advisor:
    skipExcluded: true
